site_name: 参与开源
site_url: https://erdengk.github.io/gsoc-analyse/
site_author: erdengk
site_description: >-
  参与开源

repo_name: open-source-analyse
repo_url: https://github.com/erdengk/gsoc-analyse

copyright: Copyright &copy; 2021-present <a href="https://github.com/erdengk" target="_blank" rel="noopener noreferrer">erdengk</a>

theme:
  name: material
  language: zh

  palette:
    primary: blue
    accent: light blue

  custom_dir: overrides

  icon:
    repo: fontawesome/brands/github



  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - search.suggest
    - search.highlight
#    # - navigation.instant
#    # - navigation.expand
#    # - navigation.sections
#    - navigation.tracking
#    # - navigation.tabs
#    # - navigation.tabs.sticky
#    - navigation.top
#    # - navigation.indexes
#    - search.highlight
#    - search.share
#    - search.suggest
#    # - toc.integrate
#    - content.code.annotate
plugins:
  - minify:
      minify_html: true
  - search:
  - git-revision-date-localized:
      type: date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/erdengk/gsoc-analyse

nav:
  - 前言: "index.md"
  - 基础知识(建设中): "cn/base.md"
  - 开始参与开源(建设中): "cn/start.md"
  - 开源活动总结(不断更新中): "cn/activity.md"
  - 贡献指南 : "contribution/Contribution Guidelines.md"
  - GSoC:
    - "GSoC": "cn/gsoc/index.md"
    - "前人经验（文章）" : "cn/gsoc/experience-docs.md"
    - "前人经验（视频）" : "cn/gsoc/experience-video.md"
    - "GSoC2023": "cn/gsoc/GSoC2023/GSoC2023.md"
    - "GSoC2022": "cn/gsoc/GSoC2022/GSoC2022.md"
    - "GSoC2021": "cn/gsoc/GSoC2021/GSoC2021.md"
  - 暑期之夏(OSPP):
    - "OSPP" : "cn/ospp/index.md"
    - "OSPP2022": "cn/ospp/OSPP2022/OSPP2022.md"
    - "前人经验" : "cn/ospp/experience.md"
  - 计算机学会开源夏令营(GLCC):
    - "GLCC": "cn/glcc/index.md"
    - "前人经验": "cn/glcc/experience.md"
    - "2022项目": "cn/glcc/GLCC2022/glcc2022.md"
    - "2022中期通过项目": "cn/glcc/GLCC2022/glcc2022middle.md"
  - 阿里巴巴编程之夏（ASoC）:
    - "ASoC": "cn/asoc/index.md"
    - "maxingg_expr": "cn/asoc/experience/1.maxingg_expr.md"
    - "lyf712_expr": "cn/asoc/experience/2.lyf712_expr.md"
    - "situ2001_expr": "cn/asoc/experience/3.situ2001_expr.md"
  - 腾讯犀牛鸟开源活动:
    - "犀牛鸟开源活动": "cn/rhino-brid/index.md"
    - "itwaix_expr": "cn/rhino-brid/experience/1.itwaix_expr.md"
  - openEuler开源活动:
    - "openEuler": "cn/openEuler/index.md"